"use server";

import { db } from "@/db";
import { orders, orderItems } from "@/db/schema";
import { eq, and, desc } from "drizzle-orm";

export async function submitOrder(orderData: any, itemsData: any[]) {
  try {
    // 1. Check if this table already has an "active" order
    const existingOrder = await db.query.orders.findFirst({
      where: and(
        eq(orders.tableNumber, orderData.tableNumber),
        eq(orders.status, "active")
      ),
    });

    let finalOrderId = "";

    if (existingOrder) {
      // 2a. TABLE HAS ACTIVE ORDER -> APPEND TO IT
      finalOrderId = existingOrder.id;
      
      // Update the main order total
      await db.update(orders)
        .set({ 
          total: existingOrder.total + orderData.total,
          // If they added a new note, append it to the old one so the chef sees both
          generalNote: orderData.generalNote 
            ? (existingOrder.generalNote ? `${existingOrder.generalNote} | ${orderData.generalNote}` : orderData.generalNote) 
            : existingOrder.generalNote
        })
        .where(eq(orders.id, finalOrderId));

      // Map the new items to the existing Order ID
      const itemsToInsert = itemsData.map(item => ({
        ...item,
        orderId: finalOrderId, 
        status: "pending" // Set new items as pending
      }));
      
      if (itemsToInsert.length > 0) {
        await db.insert(orderItems).values(itemsToInsert);
      }
      
    } else {
      // 2b. BRAND NEW ORDER FOR THIS TABLE
      finalOrderId = orderData.id; // The ID generated by the frontend
      
      await db.insert(orders).values(orderData);
      
      const itemsToInsert = itemsData.map(item => ({
        ...item,
        orderId: finalOrderId,
        status: "pending"
      }));

      if (itemsToInsert.length > 0) {
        await db.insert(orderItems).values(itemsToInsert);
      }
    }

    // Return the final Order ID so the frontend can display the correct ticket number
    return { success: true, orderId: finalOrderId };
  } catch (error) {
    console.error("Failed to submit order:", error);
    return { success: false, error: "Database error" };
  }
}

// Get Active orders for the Chef Dashboard
export async function getActiveOrders() {
  return await db.query.orders.findMany({
    where: eq(orders.status, "active"),
    with: { items: true },
    orderBy: [desc(orders.createdAt)],
  });
}

// Close an entire order
// Close an entire order OR Restore it
export async function updateOrderStatus(orderId: string, status: "completed" | "cancelled" | "active") {
    try {
      await db.update(orders)
        .set({ 
          status, 
          // If we are restoring to active, wipe the closedAt time. Otherwise, stamp it.
          closedAt: status === "active" ? null : new Date() 
        })
        .where(eq(orders.id, orderId));
      return { success: true };
    } catch (error) {
      console.error("Failed to update order:", error);
      return { success: false };
    }
  }

// ✅ NEW ACTION: Mark individual items as served by the chef
export async function updateOrderItemStatus(itemId: number, status: "pending" | "served") {
  try {
    await db.update(orderItems)
      .set({ status })
      .where(eq(orderItems.id, itemId));
    return { success: true };
  } catch (error) {
    console.error("Failed to update item status:", error);
    return { success: false };
  }
}

// Get details for a specific order (for the bill page)
export async function getOrderDetails(orderId: string) {
  try {
    return await db.query.orders.findFirst({
      where: eq(orders.id, orderId),
      with: { items: true },
    });
  } catch (error) {
    console.error("Failed to fetch order details:", error);
    return null;
  }
}

// Get Completed orders
export async function getClosedOrders() {
  return await db.query.orders.findMany({
    where: eq(orders.status, "completed"),
    with: { items: true },
    orderBy: [desc(orders.closedAt)],
    limit: 50, // Limit to recent 50 for performance
  });
}

// Get Cancelled orders
export async function getCancelledOrders() {
  return await db.query.orders.findMany({
    where: eq(orders.status, "cancelled"),
    with: { items: true },
    orderBy: [desc(orders.closedAt)],
    limit: 50, // Limit to recent 50 for performance
  });
}